### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by excentrickristy** [virtua-tech/jakartaee-tutorial-playbook#20] opened 2023-11-24 21:09 UTC
@shabnammayel has requested we add Google Analytics to these pages.

The GTM code can be found here: https://www.eclipse.org/eclipse.org-common/themes/solstice/docs/#gdpr

Thanks!

**Comment by kito99** [comment] 2023-12-14 13:59
This can be done in the jakarta-documentation-ui, I believe. Another good candidate for you, @jhammen.

**Comment by kito99** [comment] 2023-12-14 14:55
Actually, this is a site-wide feature that can be configured in the jakartaee-documentation project: https://docs.antora.org/antora/latest/playbook/site-keys/#google-analytics-key.

Moving the issue accordingly.

**Comment by kito99** [comment] 2024-01-04 14:35
@jhammen want to tackle this one?

**Comment by jhammen** [comment] 2024-01-11 11:02
no special expertise with GA and I have a few issues now so I'm afraid I'm going to have to pass

will say as an open source project we might want to consider open source analytics e.g. https://matomo.org/

**Comment by chrisguindon** [comment] 2024-01-11 13:51
> will say as an open source project we might want to consider open source analytics e.g. https://matomo.org/

The foundation currently only supports Google Analytics. See Eclipse Foundation Hosted Services Privacy and Acceptable Usage Policy: https://www.eclipse.org/org/documents/eclipse-foundation-hosted-services-privacy-and-acceptable-usage-policy.pdf

However, we do have plans to look at supporting Matomo this year.

@autumnfound,

@shabnammayel reached out to us this morning. The project needs help implementing this. Can you take a look at this project and investigate how we can add the following in the template to enable GA on this documentation website:

In the `<HEAD>` of the document:

```
  <!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5WLCZXC');</script>
<!-- End Google Tag Manager -->  

```

Since this website is not using our look and feel, we will also need to inject our cookie consent banner:

```
  <link rel="stylesheet" type="text/css" href="//www.eclipse.org/eclipse.org-common/themes/solstice/public/stylesheets/vendor/cookieconsent/cookieconsent.min.css" />
  <script src="//www.eclipse.org/eclipse.org-common/themes/solstice/public/javascript/vendor/cookieconsent/default.min.js"></script>  
```

**Comment by autumnfound** [comment] 2024-01-17 20:18
> Can you take a look at this project and investigate how we can add the following in the template to enable GA on this documentation website:

Started looking into this today, but it looks like the site already has GTM added and in some way configured https://github.com/jakartaee/jakartaee-documentation-ui/blob/main/src/partials/head-scripts.hbs#L2. I think I'll need more info, as I don't want to try adding a second instance or removing what's already there. I can look at adding the additional scripts for the cookie consent banner for now as a starting point though.

**Comment by excentrickristy** [comment] 2024-01-17 20:36
Maybe I should have checked to make sure we have the right repo. When I check the tutorial page here: https://jakarta.ee/learn/docs/jakartaee-tutorial/current/index.html I don't see any google analytics or tag manager installed. Maybe I'm in the wrong place?

**Comment by autumnfound** [comment] 2024-01-17 20:50
> Maybe I should have checked to make sure we have the right repo. When I check the tutorial page here: https://jakarta.ee/learn/docs/jakartaee-tutorial/current/index.html I don't see any google analytics or tag manager installed. Maybe I'm in the wrong place?

I was talking with @chrisguindon, it looks like if you don't configure the key it doesn't get added. I can add to my current patch to update as well!

**Comment by kito99** [comment] 2024-01-18 16:37
Hey @autumnfound the "correct" way to add this is here: https://docs.antora.org/antora/latest/playbook/site-keys/#google-analytics-key. What patch are you guys referring to?

**Comment by excentrickristy** [comment] 2024-01-19 22:11
I'm not seeing any google tags installed on tutorial yet, is there something we missed?
<img width="1381" alt="image" src="https://github.com/jakartaee/jakartaee-documentation/assets/73264129/d120c6aa-8a16-455c-aa14-d0a6d4fc7e89">

**Comment by kito99** [comment] 2024-01-24 14:01
@excentrickristy my apologies; this should have been reopened. See discussion here: https://github.com/jakartaee/jakartaee-documentation/pull/21#issuecomment-1899513579.

**Comment by kito99** [comment] 2024-02-05 18:15
@autumnfound hey, sorry, picking this back up. so from what I can tell, the Antora approach isn't working and you think you need to update the partial directly?

**Comment by autumnfound** [comment] 2024-02-05 21:15
> @autumnfound hey, sorry, picking this back up. so from what I can tell, the Antora approach isn't working and you think you need to update the partial directly?

I'm not entirely sure what the root issue is, as the local build works for me with current code when I add the key to the UI build in the same way as this project. Currently, the only fix I can offer is to hardcode the analytics key in since that mechanism seems to be not working as intended. I don't have experience in Antora builds, or the stack used in this case to compile the site so I can't provide any further support for these changes

**Comment by kito99** [comment] 2024-02-12 15:01
OK, @autumnfound perhaps we should go back to your original changes to the UI itself, then. Sorry for the derailment! It seemed like a good idea...

**Comment by excentrickristy** [comment] 2024-03-13 16:27
hello! Is there any update on the progress for this?

**Comment by kito99** [comment] 2024-03-14 01:50
Thanks for the reminder, @excentrickristy. There is an open PR I'll test oout this weekend.

**Comment by kito99** [comment] 2024-03-18 02:11
thanks @autumnfound! @excentrickristy this has been merged and deployed.

**Closed as completed by kito99** 2024-03-18 02:11 UTC
Labels: good first issue, help wanted
